language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
script:
- grunt build
after_success:
- cd dist
#- find . -type f -exec curl -u $inukftpuser:$inukftppw --ftp-create-dirs -T {} ftp://ftp.chillville.ch/{} \;